service: karapaia-matome-api

useDotenv: true

configValidationMode: error

provider:
  name: aws
  region: ap-northeast-1
  runtime: nodejs14.x
  timeout: 30
  memorySize: 512
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'dynamodb:*'
          Resource:
            - 'arn:aws:dynamodb:ap-northeast-1:*:*'
  # CloudWatch Logsの有効期限を設定する
  logRetentionInDays: 7
  apiGateway:
    shouldStartNameWithService: true
  # environment:
  #   # TCP 接続を再利用してより効率的に通信できるようにする
  #   - AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1' 
  # オプション
  lambdaHashingVersion: 20201221

plugins:
  - serverless-webpack
  - serverless-offline

functions:
  getPosts:
    handler: src/handler.getKarapaiaPosts
    events:
      - http:
          method: GET
          path: posts

  savePosts:
    handler: src/handler.saveKarapaiaPosts
    # events:
    #   - schedule: rate(1 day) # 毎日実行

resources:
  Resources:
    # Create DynamoDB
    DynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: karapaia_matome
        AttributeDefinitions:
          - AttributeName: title
            AttributeType: S
          - AttributeName: createdAt
            AttributeType: S
        KeySchema:
          - AttributeName: title
            KeyType: HASH
          - AttributeName: createdAt
            KeyType: RANGE
        ProvisionedThroughput: # スループット
          ReadCapacityUnits: 1 # 1RCUは1秒間に2回の読み込み、または結果整合性のある1回の読み込み
          WriteCapacityUnits: 1 # 一秒ごと何回 書き込めるか。

custom:
  serverless-offline:
    host: 0.0.0.0
    httpPort: 9000
